--- #YAML:1.0
name:               HTML-GoogleMapsV3
version:            0.01
abstract:           Draw Maps using the Google V3 API
author:
    - David Peters (davidp@electronf.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Geo::Google:   0.05
    Test::Simple:  0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
